baseURL: https://furuy.com/
title: "Furkan Uysal"
paginate: 10
theme: "PaperMod"
canonifyURLs: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
ShowFullTextinRSS: true
enableEmoji: true
defaultContentLanguageInSubdir: true
defaultContentLanguage: tr
languages:
  tr:
    languageName: ":tr: Türkçe"
    languageCode: tr-TR
    languageAltTitle: Türkçe
    weight: 1
    menu:
      main:
      - name: 📚 Kategoriler
        url: /categories/
        weight: 20
      - name: 🧑‍💻 Hakkımda
        url: /hakkimda/
        weight: 50
      - name: 🔍 Ara
        url: /search/
        weight: 60
  en:
    languageName: ":us: English"
    languageCode: en-US
    languageAltTitle: English
    weight: 2
    menu:
      main:
      - name: 📚 Categories
        url: /categories/
        weight: 20
      - name: 🧑‍💻 About
        url: /about/
        weight: 50
      - name: 🔍 Search
        url: /search/
        weight: 60


publishDir: docs
permalinks:
  posts: '/:filename/'

outputs:
    home:
        - HTML
        - RSS
        - JSON

minify:
  disableXML: true
  minifyOutput: true

params:
#  homeInfoParams:
#    Title: Welcome to my cyber corner! 🌐
#    Content: I'm trying to create useful content related to [my interests](/categories/) on my blog. 💻
  env: production
  title: "Furkan Uysal"
  description: "Tech-focused personal blog."
  author: Furkan Uysal
  DateFormat: "January 2, 2006"
  displayFullLangName: true
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  disableSpecial1stPost: true
  disableScrollToTop: true
  comments: true
  hidemeta: false
  hideSummary: true
  ShowToc: true
  TocOpen: true
  enableGitInfo: true
  ShowLastMod: true
  assets:
    disableHLJS: false # to disable highlight.js
    disableFingerprinting: true
    favicon: "/assets/img/favicon.ico"
    favicon16x16: "/assets/img/favicon-16x16.png"
    favicon32x32: "/assets/img/favicon-32x32.png"
    apple_touch_icon: "/assets/img/apple-touch-icon.png"
    safari_pinned_tab: "/assets/img/logo.svg"
    theme_color: "#000000"
    msapplication_TileColor: "#000000"

  label:
    text: "Furkan Uysal"
    icon: "/assets/img/logo.svg"
    iconHeight: 35

  socialIcons:
    - name: mastodon
      title: "Mastodon"
      url: "https://mastodon.social/@furk"
    - name: github
      title: "GitHub"
      url: "https://github.com/furkun"
    - name: RSS
      title: "RSS (Türkçe 🇹🇷)"
      url: "/tr/index.xml"
    - name: RSS
      title: "RSS (English 🇺🇸)"
      url: "/en/index.xml"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page
    relative: true # To use relative path for cover image, used in hugo Page-bundles
    linkFullImages: true

  editPost:
    URL: "https://github.com/furkun/furuy.com/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    ignoreLocation: true
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
    
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: false
    simple: true
  twitter:
    disable: false
    enableDNT: true
    simple: true
  vimeo:
    disable: false
    enableDNT: true
    simple: true
  youtube:
    disable: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
